//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.34011
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace Nfe.nfe
{
    using System.Xml.Serialization;
    using Nfe.Entidade;
    using Nfe.Negocio;
    using Nfe.Negocio.Geral;
    using Nfe.Model;
    using System.Collections.Generic;
    using System;

   
    #region Inicial

    
    public partial class TNFe
    {
        public TNFe()
        {

        }
        public TNFe(Entidade_NotaFiscal ObjNotaFiscal)
        {
            this.infNFe = new TNFeInfNFe(ObjNotaFiscal);
        }
    }
    #endregion

    #region A. Dados da Nota Fiscal eletrônica
    public partial class TNFeInfNFe
    {

        public TNFeInfNFe()
        {

        }
        public TNFeInfNFe(Entidade_NotaFiscal ObjNotaFiscalInf)
        {
            NegocioFuncoesGerais ObjFunc = new NegocioFuncoesGerais();

            string cNFOut = string.Empty;
            string cDVOut = string.Empty;

            this.versao = "3.10";
            if (ObjNotaFiscalInf.ChaveAcessoNfe == string.Empty)
            {
                this.Id = "NFe" + ObjFunc.GerarChaveAcessoNfe(ObjNotaFiscalInf.Loja, ObjNotaFiscalInf.CdFornecedor, ObjNotaFiscalInf.cUf.ToString(), ObjNotaFiscalInf.DtEmissao, ObjNotaFiscalInf.EntEmit.CpfCnpj.Trim(), ObjNotaFiscalInf.ModNfe.ToString(), ObjNotaFiscalInf.sSerieNf.Trim(), ObjNotaFiscalInf.NotaFiscal.ToString().PadLeft(9, '0'), ObjNotaFiscalInf.TpEmis.ToString().Trim(), ObjNotaFiscalInf.Lote, out cNFOut, out cDVOut);
            }
            else
            {
                this.Id = "NFe" + ObjNotaFiscalInf.ChaveAcessoNfe;
                cNFOut = ObjNotaFiscalInf.CdNfe.ToString().Trim().Length == 7 ? "0" + ObjNotaFiscalInf.CdNfe.ToString().Trim() : ObjNotaFiscalInf.CdNfe.ToString();
                cDVOut = ObjNotaFiscalInf.ChaveAcessoNfe.Substring(ObjNotaFiscalInf.ChaveAcessoNfe.Length - 1, 1);
            }
            ObjNotaFiscalInf.cNF = cNFOut;
            ObjNotaFiscalInf.CdNfe = int.Parse(cDVOut);
            this.ide = new TNFeInfNFeIde(ObjNotaFiscalInf);
            this.emit = new TNFeInfNFeEmit(ObjNotaFiscalInf);

            if (ObjNotaFiscalInf.EntDest.CpfCnpj.Trim() != "99999999999")
                this.dest = new TNFeInfNFeDest(ObjNotaFiscalInf);


            if (ObjNotaFiscalInf.EntLocalEntrega != null)
                this.entrega = new TLocal(ObjNotaFiscalInf);

            List<TNFeInfNFeDet> ListItem = new List<TNFeInfNFeDet>();

            foreach (var item in ObjNotaFiscalInf.EntItemNotaFiscal)
            {
                ListItem.Add(new TNFeInfNFeDet(item, 0, ObjNotaFiscalInf.sSerieNf,ObjNotaFiscalInf.Loja));
            }
            this.det = ListItem.ToArray();
            this.total = new TNFeInfNFeTotal(ObjNotaFiscalInf);
            this.transp = new TNFeInfNFeTransp(ObjNotaFiscalInf);

            List<TNFeInfNFePag> ListPag = new List<TNFeInfNFePag>();

            if (ObjNotaFiscalInf.EntDuplicata != null)
            {
                if (ObjNotaFiscalInf.sSerieNf != "9")
                    this.cobr = (new TNFeInfNFeCobr(ObjNotaFiscalInf));
                else
                {
                    foreach (var EntDup in ObjNotaFiscalInf.EntDuplicata)
                    {
                        ListPag.Add(new TNFeInfNFePag(EntDup));
                    }

                    this.pag = ListPag.ToArray();
                }
            }
            else
            {

            }

            if (ObjNotaFiscalInf.Observacao.Trim() != string.Empty)
            {
                this.infAdic = new TNFeInfNFeInfAdic(ObjNotaFiscalInf);
            }
        }
    }
    #endregion

    #region B -Identificação da Nota Fiscal eletrônica
    public partial class TNFeInfNFeIde
    {
        public TNFeInfNFeIde()
        {

        }
        public TNFeInfNFeIde(Entidade_NotaFiscal ObjNotaFiscalIde)
        {
            string cDivRandom = string.Empty;
            List<TNFeInfNFeIdeNFref> ListObjNfReferida;
            TNFeInfNFeIdeNFref ObjNfReferida;

            this.cUF = (TCodUfIBGE)NegocioFuncoesGerais.RetornoCodigoIbge(ObjNotaFiscalIde.cUf);
            this.cNF = ObjNotaFiscalIde.cNF;
            this.natOp = ObjNotaFiscalIde.NaturezaOperacao.Trim();
            if (ObjNotaFiscalIde.ModNfe == 55)
                this.mod = TMod.Item55;
            else
                this.mod = TMod.Item65;
            this.serie = ObjNotaFiscalIde.sSerieNf.Trim();
            this.nNF = ObjNotaFiscalIde.NotaFiscal.ToString();
            this.dhEmi = string.Format("{0:s}", Convert.ToDateTime(ObjNotaFiscalIde.DtEmissao)) + "-03:00";

            if (ObjNotaFiscalIde.sSerieNf != "9")
            {
                if (ObjNotaFiscalIde.TpNfe == "E")
                    this.dhSaiEnt = string.Format("{0:s}", Convert.ToDateTime(ObjNotaFiscalIde.DtEntrada)) + "-03:00";
                else
                    this.dhSaiEnt = string.Format("{0:s}", Convert.ToDateTime(ObjNotaFiscalIde.DtEmissao)) + "-03:00";
            }
            if (ObjNotaFiscalIde.TpNfe == "E")
                this.tpNF = TNFeInfNFeIdeTpNF.Item0;
            else
                this.tpNF = TNFeInfNFeIdeTpNF.Item1;

            //-- 1=Operação interna| 2=Operação interestadual | 3=Operação com exterior.\\
            if (ObjNotaFiscalIde.sSerieNf != "9")
            {
                if (ObjNotaFiscalIde.TipoOperacao == 1)
                    this.idDest = TNFeInfNFeIdeIdDest.Item1;
                else if (ObjNotaFiscalIde.TipoOperacao == 2)
                    this.idDest = TNFeInfNFeIdeIdDest.Item2;
                else
                    this.idDest = TNFeInfNFeIdeIdDest.Item3;
            }
            else
                this.idDest = TNFeInfNFeIdeIdDest.Item1;


            this.finNFe = (TFinNFe)ObjNotaFiscalIde.TipoFInalidadeNfe - 1;

            this.cMunFG = ObjNotaFiscalIde.EntEmit.cMunicipio.ToString();

            if (ObjNotaFiscalIde.ModNfe == 55)
                this.tpImp = TNFeInfNFeIdeTpImp.Item1;
            else
                this.tpImp = TNFeInfNFeIdeTpImp.Item4;

            if (ObjNotaFiscalIde.TpEmis == 1)
                this.tpEmis = TNFeInfNFeIdeTpEmis.Item1;
            else if (ObjNotaFiscalIde.TpEmis == 2)
                this.tpEmis = TNFeInfNFeIdeTpEmis.Item2;
            else if (ObjNotaFiscalIde.TpEmis == 6)
                this.tpEmis = TNFeInfNFeIdeTpEmis.Item6;
            else if (ObjNotaFiscalIde.TpEmis == 7)
                this.tpEmis = TNFeInfNFeIdeTpEmis.Item7;
            //Digito Verificador
            this.cDV = ObjNotaFiscalIde.CdNfe.ToString().Trim();

            if (ObjNotaFiscalIde.TpAmbiente == "PROD")
                this.tpAmb = TAmb.Item1;
            else
                this.tpAmb = TAmb.Item2;
            //0=Normal;
            //1=Consumidor final;
            if (ObjNotaFiscalIde.ModNfe == 55)
            {
                if (ObjNotaFiscalIde.EntDest.IE.Trim() == string.Empty)
                    this.indFinal = TNFeInfNFeIdeIndFinal.Item1;
                else
                    this.indFinal = TNFeInfNFeIdeIndFinal.Item0;
            }
            else
                this.indFinal = TNFeInfNFeIdeIndFinal.Item1;

            //0=Não se aplica (por exemplo, Nota Fiscal complementar ou de ajuste);
            //1=Operação presencial;
            //2=Operação não presencial, pela Internet;
            //3=Operação não presencial, Teleatendimento;
            //4=NFC-e em operação com entrega a domicílio;
            //9=Operação não presencial, outros.

            this.indPag = (TNFeInfNFeIdeIndPag)ObjNotaFiscalIde.TipoPagamento;
            this.indPres = TNFeInfNFeIdeIndPres.Item1;

            //0=Emissão de NF-e com aplicativo do contribuinte;
            //1=Emissão de NF-e avulsa pelo Fisco;
            //2=Emissão de NF-e avulsa, pelo contribuinte com seu certificado digital, através do site do Fisco;
            //3=Emissão NF-e pelo contribuinte com aplicativo fornecido pelo Fisco.

            this.procEmi = TProcEmi.Item0;

            this.verProc = "SoftLife NFe 2.0";

            if (ObjNotaFiscalIde.TpEmis == 2)
            {
                this.xJust = "Sistema Inoperante";
                this.dhCont = string.Format("{0:s}", ObjNotaFiscalIde.DataHoraConting + "-03:00");
            }

            if (ObjNotaFiscalIde.NotaFiscalReferida != null)
            {
                //ListObjNfReferida = new List<TNFeInfNFeIdeNFref>(new List<TNFeInfNFeIdeNFref>(ObjNotaFiscalIde));
                ListObjNfReferida = new List<TNFeInfNFeIdeNFref>();
                foreach (var NotaFornecedor in ObjNotaFiscalIde.NotaFiscalReferida)
                {
                    ObjNfReferida = new TNFeInfNFeIdeNFref(NotaFornecedor);
                    ListObjNfReferida.Add(ObjNfReferida);
                }
                this.NFref = ListObjNfReferida.ToArray();
            }
        }
    }

    #region B A. Documento Fiscal Referenciado
    public partial class TNFeInfNFeIdeNFref
    {
        public TNFeInfNFeIdeNFref()
        {

        }
        public TNFeInfNFeIdeNFref(Entidade_NotaFiscalReferida ObjNfeRef)
        {
            if (ObjNfeRef.SerieNfRef.Trim() == "D1")
            {
                this.ItemElementName = ItemChoiceType1.refECF;
                this.Item = new TNFeInfNFeIdeNFrefRefECF(ObjNfeRef);
            }
            else
            {
                this.ItemElementName = ItemChoiceType1.refNFe;
                this.Item = ObjNfeRef.TxChAcessoNfeReferida;
            }
        }
    }
    public partial class TNFeInfNFeIdeNFrefRefECF
    {
        public TNFeInfNFeIdeNFrefRefECF()
        {

        }
        public TNFeInfNFeIdeNFrefRefECF(Entidade_NotaFiscalReferida ObjNfeRefECF)
        {
            this.mod = TNFeInfNFeIdeNFrefRefECFMod.Item2D;
            this.nECF = "1";
            this.nCOO = ObjNfeRefECF.COO.ToString();
        }
    }
    #endregion

    #endregion

    #region C. Identificação do Emitente da Nota Fiscal eletrônica
    public partial class TNFeInfNFeEmit
    {
        public TNFeInfNFeEmit()
        {

        }
        public TNFeInfNFeEmit(Entidade_NotaFiscal ObjNotaFiscalEmit)
        {
            this.ItemElementName = ItemChoiceType2.CNPJ;
            this.Item = ObjNotaFiscalEmit.EntEmit.CpfCnpj;
            this.xNome = ObjNotaFiscalEmit.EntEmit.Nome;
            this.xFant = ObjNotaFiscalEmit.EntEmit.RazaoSocial;
            this.enderEmit = new TEnderEmi(ObjNotaFiscalEmit);
            this.IE = ObjNotaFiscalEmit.EntEmit.IE;
            if (FuncoesGerais.ParamatroTributacaoEmpresa() == "0")
                this.CRT = TNFeInfNFeEmitCRT.Item1;
            else if (FuncoesGerais.ParamatroTributacaoEmpresa() == "1")
                this.CRT = TNFeInfNFeEmitCRT.Item2;
            else
                this.CRT = TNFeInfNFeEmitCRT.Item3;
        }
    }
    public partial class TEnderEmi
    {
        public TEnderEmi()
        {

        }
        public TEnderEmi(Entidade_NotaFiscal ObjNotaFiscalEndereco)
        {
            this.xLgr = ObjNotaFiscalEndereco.EntEmit.Lagradouro;
            this.nro = ObjNotaFiscalEndereco.EntEmit.Numero.ToString();
            if (ObjNotaFiscalEndereco.EntEmit.Complemento != null && ObjNotaFiscalEndereco.EntEmit.Complemento != string.Empty)
                this.xCpl = ObjNotaFiscalEndereco.EntEmit.Complemento;
            this.xBairro = ObjNotaFiscalEndereco.EntEmit.Bairro;
            this.cMun = ObjNotaFiscalEndereco.EntEmit.cMunicipio.ToString();
            this.xMun = ObjNotaFiscalEndereco.EntEmit.sMunicipio;
            this.UF = (TUfEmi)NegocioFuncoesGerais.RetornoCodigoUF(ObjNotaFiscalEndereco.EntEmit.sUf);
            this.CEP = ObjNotaFiscalEndereco.EntEmit.sCep;
            this.cPais = TEnderEmiCPais.Item1058;
            this.xPais = TEnderEmiXPais.BRASIL;
            this.fone = ObjNotaFiscalEndereco.EntEmit.Telefone;
        }
    }
    #endregion

    #region E. Identificação do Destinatário da Nota Fiscal eletrônica
    public partial class TNFeInfNFeDest
    {
        public TNFeInfNFeDest()
        {

        }
        public TNFeInfNFeDest(Entidade_NotaFiscal ObjNotaFiscalDest)
        {
            if (ObjNotaFiscalDest.TpAmbiente == "PROD")
            {
                if (ObjNotaFiscalDest.EntDest.CpfCnpj.Trim().Length == 11)
                    this.ItemElementName = ItemChoiceType3.CPF;
                else
                    this.ItemElementName = ItemChoiceType3.CNPJ;

                this.Item = ObjNotaFiscalDest.EntDest.CpfCnpj.Trim();
                this.xNome = ObjNotaFiscalDest.EntDest.Nome;

                if (ObjNotaFiscalDest.sSerieNf != "9")
                {
                    if (ObjNotaFiscalDest.EntDest.IE.Trim() == string.Empty)
                    {
                        if (ObjNotaFiscalDest.EntDest.FlIsento)
                            this.indIEDest = TNFeInfNFeDestIndIEDest.Item2;
                        else
                            this.indIEDest = TNFeInfNFeDestIndIEDest.Item9;
                    }
                    else
                    {
                        this.indIEDest = TNFeInfNFeDestIndIEDest.Item1;
                        this.IE = ObjNotaFiscalDest.EntDest.IE.Trim();
                    }
                }
                else
                    this.indIEDest = TNFeInfNFeDestIndIEDest.Item9;
            }
            else
            {
                this.ItemElementName = ItemChoiceType3.CNPJ;
                this.Item = "99999999000191";
                this.xNome = "NF-E EMITIDA EM AMBIENTE DE HOMOLOGACAO - SEM VALOR FISCAL";
                this.indIEDest = TNFeInfNFeDestIndIEDest.Item9;
            }

            if (ObjNotaFiscalDest.sSerieNf != "9")
                this.enderDest = new TEndereco(ObjNotaFiscalDest);
        }
    }
    public partial class TEndereco
    {
        public TEndereco()
        {

        }
        public TEndereco(Entidade_NotaFiscal ObjNotaFiscalTEndereco)
        {
            this.xLgr = ObjNotaFiscalTEndereco.EntDest.Lagradouro;
            this.nro = ObjNotaFiscalTEndereco.EntDest.Numero;
            if (ObjNotaFiscalTEndereco.EntDest.Complemento != null && ObjNotaFiscalTEndereco.EntDest.Complemento != string.Empty)
                this.xCpl = ObjNotaFiscalTEndereco.EntDest.Complemento;
            this.xBairro = ObjNotaFiscalTEndereco.EntDest.Bairro;
            this.cMun = ObjNotaFiscalTEndereco.EntDest.cMunicipio.ToString();
            this.xMun = ObjNotaFiscalTEndereco.EntDest.sMunicipio;
            this.UF = (TUf)NegocioFuncoesGerais.RetornoCodigoUF(ObjNotaFiscalTEndereco.EntDest.sUf);
            this.CEP = ObjNotaFiscalTEndereco.EntDest.sCep;
            this.cPais = "1058";// Tpais.Item1058;
            this.xPais = "Brasil";
        }
    }
    #endregion

    #region G. Identificação do Local de Entrega
    public partial class TLocal
    {
        public TLocal() { }
        public TLocal(Entidade_NotaFiscal ObjNotaFiscalLocal)
        {
            if (ObjNotaFiscalLocal.EntDest.CpfCnpj.Trim().Length == 11)
            {
                this.ItemElementName = ItemChoiceType4.CPF;
            }
            else
            {
                this.ItemElementName = ItemChoiceType4.CNPJ;
            }
            this.Item = ObjNotaFiscalLocal.EntDest.CpfCnpj;
            this.xLgr = ObjNotaFiscalLocal.EntLocalEntrega.Lagradouro;
            this.nro = ObjNotaFiscalLocal.EntLocalEntrega.Numero;
            if (ObjNotaFiscalLocal.EntLocalEntrega.Complemento != null && ObjNotaFiscalLocal.EntLocalEntrega.Complemento != string.Empty)
                this.xCpl = ObjNotaFiscalLocal.EntLocalEntrega.Complemento;
            this.xBairro = ObjNotaFiscalLocal.EntLocalEntrega.Bairro;
            this.cMun = ObjNotaFiscalLocal.EntLocalEntrega.cMunicipio.ToString();
            this.xMun = ObjNotaFiscalLocal.EntLocalEntrega.sMunicipio.ToString();
            this.UF = (TUf)NegocioFuncoesGerais.RetornoCodigoUF(ObjNotaFiscalLocal.EntLocalEntrega.sUf);
        }
    }
    #endregion

    #region H. Detalhamento de Produtos e Serviços da NF-e
    public partial class TNFeInfNFeDet
    {
        public TNFeInfNFeDet()
        {

        }
        public TNFeInfNFeDet(Entidade_ItemNotaFiscal ObjNfeDet, int it, string serienf, int loja)
        {
            this.nItem = ObjNfeDet.NrSeqItem.ToString();
            this.prod = new TNFeInfNFeDetProd(ObjNfeDet);

            this.imposto = new TNFeInfNFeDetImposto(ObjNfeDet, serienf, loja);

        }
    }
    #endregion

    #region I - Produtos e Serviços da NF-e
    public partial class TNFeInfNFeDetProd
    {
        public TNFeInfNFeDetProd()
        {

        }
        public TNFeInfNFeDetProd(Entidade_ItemNotaFiscal ObjNfeDetProd)
        {
            this.cProd = ObjNfeDetProd.CodigoProduto.ToString();
            this.cEAN = string.Empty;
            this.cEANTrib = string.Empty;
            this.xProd = ObjNfeDetProd.DescricaoProdutos;
            this.NCM = ObjNfeDetProd.NCM;
            //this.CFOP = (TCfop)NegocioFuncoesGerais.RetornoCodigoCFOP(ObjNfeDetProd.CFOP);
            this.CFOP = ObjNfeDetProd.CFOP;
            this.uCom = ObjNfeDetProd.Unidade;
            this.qCom = string.Format("{0:N4}", ObjNfeDetProd.Qtd).ToString().Replace(".", "").Replace(",", ".");
            this.vUnCom = string.Format("{0:N10}", ObjNfeDetProd.ValorUnitario).ToString().Replace(".", "").Replace(",", ".");
            this.vProd = string.Format("{0:N2}", ObjNfeDetProd.ValorTotal).ToString().Replace(".", "").Replace(",", ".");
            this.uTrib = ObjNfeDetProd.Unidade;
            this.qTrib = string.Format("{0:N4}", ObjNfeDetProd.Qtd).ToString().Replace(".", "").Replace(",", ".");
            this.vUnTrib = string.Format("{0:N10}", ObjNfeDetProd.ValorUnitario).ToString().Replace(".", "").Replace(",", ".");
            if (ObjNfeDetProd.Desconto > 0)
                this.vDesc = string.Format("{0:N2}", ObjNfeDetProd.Desconto).ToString().Replace(".", "").Replace(",", ".");
            this.indTot = TNFeInfNFeDetProdIndTot.Item1;
        }
    }
    #endregion

    #region M. Tributos incidentes no Produto ou Serviço
    public partial class TNFeInfNFeDetImposto
    {
        public TNFeInfNFeDetImposto()
        { }
        public TNFeInfNFeDetImposto(Entidade_ItemNotaFiscal ObjNotaFiscalImposto, string Objserienf,int loja)
        {
            if (Objserienf != "9")
                this.Items = new object[] { new object(), new object() };
            else
                this.Items = new object[] { new object() };

            if (ObjNotaFiscalImposto.CSTICMS != string.Empty)
            {
                this.Items[0] = new TNFeInfNFeDetImpostoICMS(ObjNotaFiscalImposto, loja);
            }
            if (ObjNotaFiscalImposto.CSTPI != string.Empty && Objserienf != "9")
            {
                this.Items[1] = new TIpi(ObjNotaFiscalImposto);
            }
            if (ObjNotaFiscalImposto.CSTCOFINS != string.Empty)
            {
                this.COFINS = new TNFeInfNFeDetImpostoCOFINS(ObjNotaFiscalImposto);
            }
            if (ObjNotaFiscalImposto.CSTPIS != string.Empty)
            {
                this.PIS = new TNFeInfNFeDetImpostoPIS(ObjNotaFiscalImposto);
            }
        }
    }

    #region ICMS

    #region IMPOSTO
    public partial class TNFeInfNFeDetImpostoICMS
    {
        public TNFeInfNFeDetImpostoICMS() { }
        public TNFeInfNFeDetImpostoICMS(Entidade_ItemNotaFiscal ObjNotaFiscalImpostoICMS,int loja)
        {
            if (FuncoesGerais.ParamatroTributacaoEmpresa(loja) == "S")
            {
                if (ObjNotaFiscalImpostoICMS.ValorTotalIcms != 0)
                    this.Item = new TNFeInfNFeDetImpostoICMSICMS00(ObjNotaFiscalImpostoICMS);
                else
                    this.Item = new TNFeInfNFeDetImpostoICMSICMSSN102(ObjNotaFiscalImpostoICMS);
            }
            else if (ObjNotaFiscalImpostoICMS.CSTICMS == "00")
                this.Item = new TNFeInfNFeDetImpostoICMSICMS00(ObjNotaFiscalImpostoICMS);
            else if (ObjNotaFiscalImpostoICMS.CSTICMS == "10")
                this.Item = new TNFeInfNFeDetImpostoICMSICMS10(ObjNotaFiscalImpostoICMS);
            else if (ObjNotaFiscalImpostoICMS.CSTICMS == "20")
                this.Item = new TNFeInfNFeDetImpostoICMSICMS20(ObjNotaFiscalImpostoICMS);
            else if (ObjNotaFiscalImpostoICMS.CSTICMS == "30")
                this.Item = new TNFeInfNFeDetImpostoICMSICMS30(ObjNotaFiscalImpostoICMS);
            else if (ObjNotaFiscalImpostoICMS.CSTICMS == "40" || ObjNotaFiscalImpostoICMS.CSTICMS == "41" || ObjNotaFiscalImpostoICMS.CSTICMS == "50")
                this.Item = new TNFeInfNFeDetImpostoICMSICMS40(ObjNotaFiscalImpostoICMS);
            else if (ObjNotaFiscalImpostoICMS.CSTICMS == "51")
                this.Item = new TNFeInfNFeDetImpostoICMSICMS51(ObjNotaFiscalImpostoICMS);
            else if (ObjNotaFiscalImpostoICMS.CSTICMS == "60")
                this.Item = new TNFeInfNFeDetImpostoICMSICMS60(ObjNotaFiscalImpostoICMS);
            else if (ObjNotaFiscalImpostoICMS.CSTICMS == "70")
                this.Item = new TNFeInfNFeDetImpostoICMSICMS70(ObjNotaFiscalImpostoICMS);
            else if (ObjNotaFiscalImpostoICMS.CSTICMS == "90")
                this.Item = new TNFeInfNFeDetImpostoICMSICMS90(ObjNotaFiscalImpostoICMS);
        }
    }

    #endregion

    #region ### --- CST'S --- ###

    public partial class TNFeInfNFeDetImpostoICMSUFDest
    {
        public TNFeInfNFeDetImpostoICMSUFDest()
        {

        }
        public TNFeInfNFeDetImpostoICMSUFDest(Entidade_ItemNotaFiscal ObjNotaFiscalImpostoICMSUfDest)
        {
            //this.
        }
    }

        #region  CST 101
        public partial class TNFeInfNFeDetImpostoICMSICMSSN101
    {
        public TNFeInfNFeDetImpostoICMSICMSSN101()
        {

        }
        public TNFeInfNFeDetImpostoICMSICMSSN101(Entidade_ItemNotaFiscal ObjNotaFiscalImpostoICMS101)
        {
            this.orig = (Torig)int.Parse(ObjNotaFiscalImpostoICMS101.Origem);
            this.CSOSN = TNFeInfNFeDetImpostoICMSICMSSN101CSOSN.Item101;
            this.pCredSN = "0.00";
            this.vCredICMSSN = "0.00";
        }
    }
    #endregion

    #region CST 102
    public partial class TNFeInfNFeDetImpostoICMSICMSSN102
    {
        public TNFeInfNFeDetImpostoICMSICMSSN102()
        {
        }
        public TNFeInfNFeDetImpostoICMSICMSSN102(Entidade_ItemNotaFiscal ObjNotaFiscalImpostoICMS102)
        {
            this.orig = (Torig)int.Parse(ObjNotaFiscalImpostoICMS102.Origem);
            this.CSOSN = TNFeInfNFeDetImpostoICMSICMSSN102CSOSN.Item102;
        }
    }
    #endregion

    #region CST - 00
    public partial class TNFeInfNFeDetImpostoICMSICMS00
    {
        public TNFeInfNFeDetImpostoICMSICMS00()
        { }
        public TNFeInfNFeDetImpostoICMSICMS00(Entidade_ItemNotaFiscal ObjNotaFiscalImpostoICMS00)
        {
            this.orig = (Torig)int.Parse(ObjNotaFiscalImpostoICMS00.Origem);
            this.CST = TNFeInfNFeDetImpostoICMSICMS00CST.Item00;
            this.modBC = TNFeInfNFeDetImpostoICMSICMS00ModBC.Item3;
            this.vBC = string.Format("{0:N2}", ObjNotaFiscalImpostoICMS00.ValorTotalIcms).ToString().Replace(".", "").Replace(",", ".");
            this.vICMS = string.Format("{0:N2}", ObjNotaFiscalImpostoICMS00.ValorIcms).ToString().Replace(".", "").Replace(",", ".");
            this.pICMS = string.Format("{0:N4}", ObjNotaFiscalImpostoICMS00.AliqIcms).ToString().Replace(",", ".");
        }
    }
    #endregion

    #region CST - 10
    public partial class TNFeInfNFeDetImpostoICMSICMS10
    {
        public TNFeInfNFeDetImpostoICMSICMS10()
        {

        }
        public TNFeInfNFeDetImpostoICMSICMS10(Entidade_ItemNotaFiscal ObjNotaFiscalImpostoICMS10)
        {
            this.orig = (Torig)int.Parse(ObjNotaFiscalImpostoICMS10.Origem);
            this.CST = TNFeInfNFeDetImpostoICMSICMS10CST.Item10;
            this.modBC = TNFeInfNFeDetImpostoICMSICMS10ModBC.Item3;
            this.vBC = string.Format("{0:N2}", ObjNotaFiscalImpostoICMS10.ValorTotalIcms).ToString().Replace(".", "").Replace(",", ".");
            this.vICMS = string.Format("{0:N2}", ObjNotaFiscalImpostoICMS10.ValorIcms).ToString().Replace(".", "").Replace(",", ".");
            this.pICMS = string.Format("{0:N4}", ObjNotaFiscalImpostoICMS10.AliqIcms).ToString().Replace(",", ".");
            this.modBCST = TNFeInfNFeDetImpostoICMSICMS10ModBCST.Item4;
            this.pMVAST = ObjNotaFiscalImpostoICMS10.PercMVA.ToString().Replace(".", "").Replace(",", ".");
            this.vBCST = string.Format("{0:N2}", ObjNotaFiscalImpostoICMS10.ValorIcmsBaseSub).ToString().Replace(".", "").Replace(",", ".");
            this.pICMSST = string.Format("{0:N4}", ObjNotaFiscalImpostoICMS10.AliqIcms).ToString().Replace(".", "").Replace(",", ".");
            this.vICMSST = string.Format("{0:N2}", ObjNotaFiscalImpostoICMS10.ValorIcmsSub).ToString().Replace(".", "").Replace(",", ".");
        }
    }
    #endregion

    #region CST - 20
    public partial class TNFeInfNFeDetImpostoICMSICMS20
    {
        public TNFeInfNFeDetImpostoICMSICMS20()
        {

        }
        public TNFeInfNFeDetImpostoICMSICMS20(Entidade_ItemNotaFiscal ObjNotaFiscalImpostoICMS20)
        {
            this.orig = (Torig)int.Parse(ObjNotaFiscalImpostoICMS20.Origem);
            this.CST = TNFeInfNFeDetImpostoICMSICMS20CST.Item20;
            this.modBC = TNFeInfNFeDetImpostoICMSICMS20ModBC.Item3;
            this.pRedBC = string.Format("{0:N2}", ObjNotaFiscalImpostoICMS20.PercReducao).ToString().Replace(".", "").Replace(",", ".");
            this.pICMS = string.Format("{0:N4}", ObjNotaFiscalImpostoICMS20.AliqIcms.ToString()).Replace(".", "").Replace(",", ".");
            this.vICMS = string.Format("{0:N2}", ObjNotaFiscalImpostoICMS20.ValorIcms).ToString().Replace(".", "").Replace(",", ".");
            this.vBC = string.Format("{0:N2}", ObjNotaFiscalImpostoICMS20.ValorTotalIcms).ToString().Replace(".", "").Replace(",", ".");
        }
    }
    #endregion

    #region CST - 30
    public partial class TNFeInfNFeDetImpostoICMSICMS30
    {
        public TNFeInfNFeDetImpostoICMSICMS30() { }
        public TNFeInfNFeDetImpostoICMSICMS30(Entidade_ItemNotaFiscal ObjNotaFiscalImpostoICMS30)
        {
            this.orig = (Torig)int.Parse(ObjNotaFiscalImpostoICMS30.Origem);
            this.CST = TNFeInfNFeDetImpostoICMSICMS30CST.Item30;
            this.modBCST = TNFeInfNFeDetImpostoICMSICMS30ModBCST.Item5;
            this.vBCST = string.Format("{0:N2}", ObjNotaFiscalImpostoICMS30.ValorIcmsBaseSub).ToString().Replace(".", "").Replace(",", ".");
            this.pICMSST = string.Format("{0:N4}", ObjNotaFiscalImpostoICMS30.AliqIcms).ToString().Replace(".", "").Replace(",", ".");
            this.vICMSST = string.Format("{0:N2}", ObjNotaFiscalImpostoICMS30.ValorIcmsSub).ToString().Replace(".", "").Replace(",", ".");
        }
    }
    #endregion

    #region CST - 40,41,50
    public partial class TNFeInfNFeDetImpostoICMSICMS40
    {
        public TNFeInfNFeDetImpostoICMSICMS40() { }
        public TNFeInfNFeDetImpostoICMSICMS40(Entidade_ItemNotaFiscal ObjNotaFiscalImpostoICMS40)
        {
            this.orig = (Torig)int.Parse(ObjNotaFiscalImpostoICMS40.Origem);
            if (ObjNotaFiscalImpostoICMS40.CSTICMS == "40")
                this.CST = TNFeInfNFeDetImpostoICMSICMS40CST.Item40;
            else if (ObjNotaFiscalImpostoICMS40.CSTICMS == "41")
                this.CST = TNFeInfNFeDetImpostoICMSICMS40CST.Item41;
            else if (ObjNotaFiscalImpostoICMS40.CSTICMS == "50")
                this.CST = TNFeInfNFeDetImpostoICMSICMS40CST.Item50;
        }
    }
    #endregion

    #region CST - 51
    public partial class TNFeInfNFeDetImpostoICMSICMS51
    {
        public TNFeInfNFeDetImpostoICMSICMS51() { }

        public TNFeInfNFeDetImpostoICMSICMS51(Entidade_ItemNotaFiscal ObjNotaFiscalImpostoICMS51)
        {
            this.orig = this.orig = (Torig)int.Parse(ObjNotaFiscalImpostoICMS51.Origem);
            this.CST = TNFeInfNFeDetImpostoICMSICMS51CST.Item51;
        }
    }
    #endregion

    #region CST - 60
    public partial class TNFeInfNFeDetImpostoICMSICMS60
    {
        public TNFeInfNFeDetImpostoICMSICMS60() { }
        public TNFeInfNFeDetImpostoICMSICMS60(Entidade_ItemNotaFiscal ObjNotaFiscalImpostoICMS60)
        {
            this.orig = (Torig)int.Parse(ObjNotaFiscalImpostoICMS60.Origem);
            this.CST = TNFeInfNFeDetImpostoICMSICMS60CST.Item60;
        }
    }
    #endregion

    #region CST - 70
    public partial class TNFeInfNFeDetImpostoICMSICMS70
    {
        public TNFeInfNFeDetImpostoICMSICMS70()
        {

        }
        public TNFeInfNFeDetImpostoICMSICMS70(Entidade_ItemNotaFiscal ObjNotaFiscalImpostoICMS70)
        {
            this.orig = (Torig)int.Parse(ObjNotaFiscalImpostoICMS70.Origem);
            this.CST = TNFeInfNFeDetImpostoICMSICMS70CST.Item70;
            this.modBC = TNFeInfNFeDetImpostoICMSICMS70ModBC.Item3;
            this.pRedBC = string.Format("{0:N2}", ObjNotaFiscalImpostoICMS70.PercReducao).ToString().Replace(".", "").Replace(",", ".");
            this.vBC = string.Format("{0:N2}", ObjNotaFiscalImpostoICMS70.ValorTotalIcms).ToString().Replace(".", "").Replace(",", ".");
            this.pICMS = string.Format("{0:N4}", ObjNotaFiscalImpostoICMS70.AliqIcms).ToString().Replace(".", "").Replace(",", ".");
            this.vICMS = string.Format("{0:N2}", ObjNotaFiscalImpostoICMS70.ValorIcms).ToString().Replace(".", "").Replace(",", ".");
            this.modBCST = TNFeInfNFeDetImpostoICMSICMS70ModBCST.Item4;
            this.pMVAST = string.Format("{0:N2}", ObjNotaFiscalImpostoICMS70.PercMVA).ToString().Replace(".", "").Replace(",", ".");
            this.vBCST = string.Format("{0:N2}", ObjNotaFiscalImpostoICMS70.ValorIcmsBaseSub).ToString().Replace(".", "").Replace(",", ".");
            this.pICMSST = string.Format("{0:N4}", ObjNotaFiscalImpostoICMS70.AliqIcms).ToString().Replace(".", "").Replace(",", ".");
            this.vICMSST = string.Format("{0:N2}", ObjNotaFiscalImpostoICMS70.ValorIcmsSub).ToString().Replace(".", "").Replace(",", ".");
        }
    }
    #endregion

    #region CST - 90
    public partial class TNFeInfNFeDetImpostoICMSICMS90
    {
        public TNFeInfNFeDetImpostoICMSICMS90()
        {

        }
        public TNFeInfNFeDetImpostoICMSICMS90(Entidade_ItemNotaFiscal ObjNotaFiscalImpostoICMS90)
        {
            this.orig = (Torig)int.Parse(ObjNotaFiscalImpostoICMS90.Origem);
            this.CST = TNFeInfNFeDetImpostoICMSICMS90CST.Item90;
        }

    }
    #endregion

    #endregion

    #region ### --- IPI --- ###
    public partial class TIpi
    {
        public TIpi()
        {

        }
        public TIpi(Entidade_ItemNotaFiscal ObjNotaFiscalIPI)
        {
            if (ObjNotaFiscalIPI.CSTPI == "01" || ObjNotaFiscalIPI.CSTPI == "02" || ObjNotaFiscalIPI.CSTPI == "03" || ObjNotaFiscalIPI.CSTPI == "04" || ObjNotaFiscalIPI.CSTPI == "05" || ObjNotaFiscalIPI.CSTPI == "51" || ObjNotaFiscalIPI.CSTPI == "52" || ObjNotaFiscalIPI.CSTPI == "53" || ObjNotaFiscalIPI.CSTPI == "54" || ObjNotaFiscalIPI.CSTPI == "55")
                this.Item = new TIpiIPINT(ObjNotaFiscalIPI);
            else if ((ObjNotaFiscalIPI.CSTPI == "00") || (ObjNotaFiscalIPI.CSTPI == "49") || (ObjNotaFiscalIPI.CSTPI == "50") || (ObjNotaFiscalIPI.CSTPI == "99"))
                this.Item = new TIpiIPITrib(ObjNotaFiscalIPI);

            this.cEnq = "999";
        }
    }
    #region ---- NT ----
    public partial class TIpiIPINT
    {
        public TIpiIPINT()
        {

        }
        public TIpiIPINT(Entidade_ItemNotaFiscal ObjNotaFiscalIPINT)
        {
            if (ObjNotaFiscalIPINT.CSTPI == "01")
                this.CST = TIpiIPINTCST.Item01;
            else if (ObjNotaFiscalIPINT.CSTPI == "02")
                this.CST = TIpiIPINTCST.Item02;
            else if (ObjNotaFiscalIPINT.CSTPI == "03")
                this.CST = TIpiIPINTCST.Item03;
            else if (ObjNotaFiscalIPINT.CSTPI == "04")
                this.CST = TIpiIPINTCST.Item04;
            else if (ObjNotaFiscalIPINT.CSTPI == "05")
                this.CST = TIpiIPINTCST.Item05;
            else if (ObjNotaFiscalIPINT.CSTPI == "51")
                this.CST = TIpiIPINTCST.Item51;
            else if (ObjNotaFiscalIPINT.CSTPI == "52")
                this.CST = TIpiIPINTCST.Item52;
            else if (ObjNotaFiscalIPINT.CSTPI == "53")
                this.CST = TIpiIPINTCST.Item53;
            else if (ObjNotaFiscalIPINT.CSTPI == "54")
                this.CST = TIpiIPINTCST.Item54;
            else if (ObjNotaFiscalIPINT.CSTPI == "55")
                this.CST = TIpiIPINTCST.Item55;
        }
    }
    #endregion

    #region ---- Trib ----
    public partial class TIpiIPITrib
    {
        public TIpiIPITrib()
        {

        }
        public TIpiIPITrib(Entidade_ItemNotaFiscal ObjNotaFiscalIPITrib)
        {
            string[] Ipi = new string[2];

            if (ObjNotaFiscalIPITrib.CSTPI == "00")
                this.CST = TIpiIPITribCST.Item00;
            else if (ObjNotaFiscalIPITrib.CSTPI == "49")
                this.CST = TIpiIPITribCST.Item49;
            else if (ObjNotaFiscalIPITrib.CSTPI == "50")
                this.CST = TIpiIPITribCST.Item50;
            else if (ObjNotaFiscalIPITrib.CSTPI == "99")
                this.CST = TIpiIPITribCST.Item99;


            this.ItemsElementName = new ItemsChoiceType[] { new ItemsChoiceType(), new ItemsChoiceType() };
            this.ItemsElementName[0] = ItemsChoiceType.vBC;
            Ipi[0] = string.Format("{0:N2}", ObjNotaFiscalIPITrib.ValorTotal).Replace(".", "").Replace(",", ".");
            this.ItemsElementName[1] = ItemsChoiceType.pIPI;
            Ipi[1] = ObjNotaFiscalIPITrib.AliqIpi.ToString().Replace(",", ".");
            this.vIPI = ObjNotaFiscalIPITrib.ValorIpi.ToString().Replace(",", ".");
            this.Items = Ipi;
        }
    }
    #endregion

    #endregion

    #region ### --- Pis --- ####

    public partial class TNFeInfNFeDetImpostoPIS
    {
        public TNFeInfNFeDetImpostoPIS()
        {

        }
        public TNFeInfNFeDetImpostoPIS(Entidade_ItemNotaFiscal ObjEntImpostos)
        {
            if (ObjEntImpostos.CSTPIS == "01" || ObjEntImpostos.CSTPIS == "02")
                this.Item = new TNFeInfNFeDetImpostoPISPISAliq(ObjEntImpostos);
            else if ((ObjEntImpostos.CSTPIS == "04") || (ObjEntImpostos.CSTPIS == "05") || (ObjEntImpostos.CSTPIS == "06") || (ObjEntImpostos.CSTPIS == "07") || (ObjEntImpostos.CSTPIS == "08") || (ObjEntImpostos.CSTPIS == "09"))
                this.Item = new TNFeInfNFeDetImpostoPISPISNT(ObjEntImpostos);
            else if (Convert.ToInt32(ObjEntImpostos.CSTPIS) >= 49 && Convert.ToInt32(ObjEntImpostos.CSTPIS) <= 99)
                this.Item = new TNFeInfNFeDetImpostoPISPISOutr(ObjEntImpostos);
        }
    }
    public partial class TNFeInfNFeDetImpostoPISPISAliq
    {
        public TNFeInfNFeDetImpostoPISPISAliq()
        {

        }
        public TNFeInfNFeDetImpostoPISPISAliq(Entidade_ItemNotaFiscal ObjNotaFiscalPisAliq)
        {
            if (ObjNotaFiscalPisAliq.CSTPIS == "01")
                this.CST = TNFeInfNFeDetImpostoPISPISAliqCST.Item01;
            else if (ObjNotaFiscalPisAliq.CSTPIS == "02")
                this.CST = TNFeInfNFeDetImpostoPISPISAliqCST.Item02;
            this.vBC = string.Format("{0:N2}", ObjNotaFiscalPisAliq.ValorTotal).ToString().Replace(".", "").Replace(",", ".");
            this.vPIS = string.Format("{0:N2}", ObjNotaFiscalPisAliq.ValorPis).ToString().Replace(".", "").Replace(",", ".");
            this.pPIS = string.Format("{0:N4}", ObjNotaFiscalPisAliq.AliqPis).ToString().Replace(".", "").Replace(",", ".");
        }
    }
    public partial class TNFeInfNFeDetImpostoPISPISNT
    {
        public TNFeInfNFeDetImpostoPISPISNT()
        {

        }
        public TNFeInfNFeDetImpostoPISPISNT(Entidade_ItemNotaFiscal ObjNotaFiscalPisNT)
        {
            if (ObjNotaFiscalPisNT.CSTPIS == "04")
                this.CST = TNFeInfNFeDetImpostoPISPISNTCST.Item04;
            else if (ObjNotaFiscalPisNT.CSTPIS == "05")
                this.CST = TNFeInfNFeDetImpostoPISPISNTCST.Item05;
            else if (ObjNotaFiscalPisNT.CSTPIS == "06")
                this.CST = TNFeInfNFeDetImpostoPISPISNTCST.Item06;
            else if (ObjNotaFiscalPisNT.CSTPIS == "07")
                this.CST = TNFeInfNFeDetImpostoPISPISNTCST.Item07;
            else if (ObjNotaFiscalPisNT.CSTPIS == "08")
                this.CST = TNFeInfNFeDetImpostoPISPISNTCST.Item08;
            else if (ObjNotaFiscalPisNT.CSTPIS == "09")
                this.CST = TNFeInfNFeDetImpostoPISPISNTCST.Item09;
        }
    }
    public partial class TNFeInfNFeDetImpostoPISST
    {
        public TNFeInfNFeDetImpostoPISST() { }
        public TNFeInfNFeDetImpostoPISST(Entidade_ItemNotaFiscal ObjNotaFiscalIPIST)
        {
            string[] vlPis = new string[2];
            this.ItemsElementName = new ItemsChoiceType2[] { new ItemsChoiceType2(), new ItemsChoiceType2() };
            this.ItemsElementName[0] = ItemsChoiceType2.pPIS;
            vlPis[0] = ObjNotaFiscalIPIST.AliqPis.ToString().Replace(",", ".");
            this.ItemsElementName[1] = ItemsChoiceType2.vBC;
            vlPis[1] = ObjNotaFiscalIPIST.ValorTotal.ToString().Replace(",", ".");

            this.Items = vlPis;
        }
    }
    public partial class TNFeInfNFeDetImpostoPISPISOutr
    {
        public TNFeInfNFeDetImpostoPISPISOutr()
        {

        }
        public TNFeInfNFeDetImpostoPISPISOutr(Entidade_ItemNotaFiscal ObjNotaFiscalIPIOutras)
        {
            if (ObjNotaFiscalIPIOutras.CSTPIS == "49")
            {

                this.CST = TNFeInfNFeDetImpostoPISPISOutrCST.Item49;
                this.vPIS = string.Format("{0:N2}", ObjNotaFiscalIPIOutras.ValorPis).ToString().Replace(".", "").Replace(",", ".");
                string[] vlPis = new string[2];
                this.ItemsElementName = new ItemsChoiceType1[] { new ItemsChoiceType1(), new ItemsChoiceType1() };
                this.ItemsElementName[0] = ItemsChoiceType1.vBC;
                vlPis[0] = string.Format("{0:N2}", ObjNotaFiscalIPIOutras.ValorTotal).ToString().Replace(".", "").Replace(",", ".");
                this.ItemsElementName[1] = ItemsChoiceType1.pPIS;
                vlPis[1] = string.Format("{0:N2}", ObjNotaFiscalIPIOutras.AliqPis).ToString().Replace(".", "").Replace(",", ".");

                this.Items = vlPis;
            }
            else if (ObjNotaFiscalIPIOutras.CSTPIS == "50")
                this.CST = TNFeInfNFeDetImpostoPISPISOutrCST.Item50;
            else if (ObjNotaFiscalIPIOutras.CSTPIS == "51")
                this.CST = TNFeInfNFeDetImpostoPISPISOutrCST.Item51;
            else if (ObjNotaFiscalIPIOutras.CSTPIS == "52")
                this.CST = TNFeInfNFeDetImpostoPISPISOutrCST.Item52;
            else if (ObjNotaFiscalIPIOutras.CSTPIS == "53")
                this.CST = TNFeInfNFeDetImpostoPISPISOutrCST.Item53;
            else if (ObjNotaFiscalIPIOutras.CSTPIS == "54")
                this.CST = TNFeInfNFeDetImpostoPISPISOutrCST.Item54;
            else if (ObjNotaFiscalIPIOutras.CSTPIS == "55")
                this.CST = TNFeInfNFeDetImpostoPISPISOutrCST.Item55;
            else if (ObjNotaFiscalIPIOutras.CSTPIS == "56")
                this.CST = TNFeInfNFeDetImpostoPISPISOutrCST.Item56;
            else if (ObjNotaFiscalIPIOutras.CSTPIS == "60")
                this.CST = TNFeInfNFeDetImpostoPISPISOutrCST.Item60;
            else if (ObjNotaFiscalIPIOutras.CSTPIS == "61")
                this.CST = TNFeInfNFeDetImpostoPISPISOutrCST.Item61;
            else if (ObjNotaFiscalIPIOutras.CSTPIS == "62")
                this.CST = TNFeInfNFeDetImpostoPISPISOutrCST.Item62;
            else if (ObjNotaFiscalIPIOutras.CSTPIS == "63")
                this.CST = TNFeInfNFeDetImpostoPISPISOutrCST.Item63;
            else if (ObjNotaFiscalIPIOutras.CSTPIS == "64")
                this.CST = TNFeInfNFeDetImpostoPISPISOutrCST.Item64;
            else if (ObjNotaFiscalIPIOutras.CSTPIS == "65")
                this.CST = TNFeInfNFeDetImpostoPISPISOutrCST.Item65;
            else if (ObjNotaFiscalIPIOutras.CSTPIS == "66")
                this.CST = TNFeInfNFeDetImpostoPISPISOutrCST.Item66;
            else if (ObjNotaFiscalIPIOutras.CSTPIS == "67")
                this.CST = TNFeInfNFeDetImpostoPISPISOutrCST.Item67;
            else if (ObjNotaFiscalIPIOutras.CSTPIS == "70")
                this.CST = TNFeInfNFeDetImpostoPISPISOutrCST.Item70;
            else if (ObjNotaFiscalIPIOutras.CSTPIS == "71")
                this.CST = TNFeInfNFeDetImpostoPISPISOutrCST.Item71;
            else if (ObjNotaFiscalIPIOutras.CSTPIS == "72")
                this.CST = TNFeInfNFeDetImpostoPISPISOutrCST.Item72;
            else if (ObjNotaFiscalIPIOutras.CSTPIS == "73")
                this.CST = TNFeInfNFeDetImpostoPISPISOutrCST.Item73;
            else if (ObjNotaFiscalIPIOutras.CSTPIS == "74")
                this.CST = TNFeInfNFeDetImpostoPISPISOutrCST.Item74;
            else if (ObjNotaFiscalIPIOutras.CSTPIS == "75")
                this.CST = TNFeInfNFeDetImpostoPISPISOutrCST.Item75;

            if (ObjNotaFiscalIPIOutras.CSTPIS == "50")
            {
                this.vPIS = string.Format("{0:N2}", ObjNotaFiscalIPIOutras.ValorPis).ToString().Replace(".", "").Replace(",", ".");
                string[] vlPis = new string[2];
                this.ItemsElementName = new ItemsChoiceType1[] { new ItemsChoiceType1(), new ItemsChoiceType1() };
                this.ItemsElementName[0] = ItemsChoiceType1.vBC;
                vlPis[0] = string.Format("{0:N2}", ObjNotaFiscalIPIOutras.ValorTotal).ToString().Replace(".", "").Replace(",", ".");
                this.ItemsElementName[1] = ItemsChoiceType1.pPIS;
                vlPis[1] = string.Format("{0:N2}", ObjNotaFiscalIPIOutras.AliqPis).ToString().Replace(".", "").Replace(",", ".");
                this.Items = vlPis;
            }
            else if (ObjNotaFiscalIPIOutras.CSTPIS == "99")
            {
                this.vPIS = string.Format("{0:N2}", ObjNotaFiscalIPIOutras.ValorPis).ToString().Replace(".", "").Replace(",", ".");
                string[] vlPis = new string[2];
                this.ItemsElementName = new ItemsChoiceType1[] { new ItemsChoiceType1(), new ItemsChoiceType1() };
                this.ItemsElementName[0] = ItemsChoiceType1.vBC;
                vlPis[0] = string.Format("{0:N2}", ObjNotaFiscalIPIOutras.ValorTotal).ToString().Replace(".", "").Replace(",", ".");
                this.ItemsElementName[1] = ItemsChoiceType1.pPIS;
                vlPis[1] = string.Format("{0:N2}", ObjNotaFiscalIPIOutras.AliqPis).ToString().Replace(".", "").Replace(",", ".");
                this.Items = vlPis;
            }
            else if (ObjNotaFiscalIPIOutras.CSTPIS != "49")
                this.vPIS = string.Format("{0:N2}", ObjNotaFiscalIPIOutras.ValorPis).ToString().Replace(",", ".");


        }
    }
    #endregion

    #region ### --- Cofins --- ###
    public partial class TNFeInfNFeDetImpostoCOFINS
    {
        public TNFeInfNFeDetImpostoCOFINS() { }
        public TNFeInfNFeDetImpostoCOFINS(Entidade_ItemNotaFiscal ObjNotaFiscalCofins)
        {
            if (ObjNotaFiscalCofins.CSTPIS == "01" || ObjNotaFiscalCofins.CSTPIS == "02")
                this.Item = new TNFeInfNFeDetImpostoCOFINSCOFINSAliq(ObjNotaFiscalCofins);
            else if ((ObjNotaFiscalCofins.CSTPIS == "04") || (ObjNotaFiscalCofins.CSTPIS == "05") || (ObjNotaFiscalCofins.CSTPIS == "06") || (ObjNotaFiscalCofins.CSTPIS == "07") || (ObjNotaFiscalCofins.CSTPIS == "08") || (ObjNotaFiscalCofins.CSTPIS == "09"))
                this.Item = new TNFeInfNFeDetImpostoCOFINSCOFINSNT(ObjNotaFiscalCofins);
            else if (Convert.ToInt32(ObjNotaFiscalCofins.CSTPIS) >= 49 && Convert.ToInt32(ObjNotaFiscalCofins.CSTPIS) <= 99)
                this.Item = new TNFeInfNFeDetImpostoCOFINSCOFINSOutr(ObjNotaFiscalCofins);
        }
    }
    public partial class TNFeInfNFeDetImpostoCOFINSCOFINSAliq
    {
        public TNFeInfNFeDetImpostoCOFINSCOFINSAliq()
        {

        }
        public TNFeInfNFeDetImpostoCOFINSCOFINSAliq(Entidade_ItemNotaFiscal ObjNotaFiscalCofinsAliq)
        {
            if (ObjNotaFiscalCofinsAliq.CSTCOFINS == "01")
                this.CST = TNFeInfNFeDetImpostoCOFINSCOFINSAliqCST.Item01;
            else if (ObjNotaFiscalCofinsAliq.CSTCOFINS == "02")
                this.CST = TNFeInfNFeDetImpostoCOFINSCOFINSAliqCST.Item02;

            this.vBC = string.Format("{0:N2}", ObjNotaFiscalCofinsAliq.ValorTotal).ToString().Replace(".", "").Replace(",", ".");
            this.pCOFINS = string.Format("{0:N2}", ObjNotaFiscalCofinsAliq.AliqCofins).ToString().Replace(".", "").Replace(",", ".");
            this.vCOFINS = string.Format("{0:N2}", ObjNotaFiscalCofinsAliq.ValorCofins).ToString().Replace(".", "").Replace(",", ".");
        }
    }
    public partial class TNFeInfNFeDetImpostoCOFINSCOFINSNT
    {
        public TNFeInfNFeDetImpostoCOFINSCOFINSNT()
        {

        }
        public TNFeInfNFeDetImpostoCOFINSCOFINSNT(Entidade_ItemNotaFiscal ObjNotaFiscalCOFINSNT)
        {
            if (ObjNotaFiscalCOFINSNT.CSTPIS == "04")
                this.CST = TNFeInfNFeDetImpostoCOFINSCOFINSNTCST.Item04;
            else if (ObjNotaFiscalCOFINSNT.CSTPIS == "05")
                this.CST = TNFeInfNFeDetImpostoCOFINSCOFINSNTCST.Item05;
            else if (ObjNotaFiscalCOFINSNT.CSTPIS == "06")
                this.CST = TNFeInfNFeDetImpostoCOFINSCOFINSNTCST.Item06;
            else if (ObjNotaFiscalCOFINSNT.CSTPIS == "07")
                this.CST = TNFeInfNFeDetImpostoCOFINSCOFINSNTCST.Item07;
            else if (ObjNotaFiscalCOFINSNT.CSTPIS == "08")
                this.CST = TNFeInfNFeDetImpostoCOFINSCOFINSNTCST.Item08;
            else if (ObjNotaFiscalCOFINSNT.CSTPIS == "09")
                this.CST = TNFeInfNFeDetImpostoCOFINSCOFINSNTCST.Item09;
        }
    }
    public partial class TNFeInfNFeDetImpostoCOFINSCOFINSOutr
    {
        public TNFeInfNFeDetImpostoCOFINSCOFINSOutr() { }
        public TNFeInfNFeDetImpostoCOFINSCOFINSOutr(Entidade_ItemNotaFiscal ObjNotaFiscalCofinsOutr)
        {
            if (ObjNotaFiscalCofinsOutr.CSTPIS == "49")
            {
                this.CST = TNFeInfNFeDetImpostoCOFINSCOFINSOutrCST.Item49;
                string[] vlCofins = new string[2];
                this.ItemsElementName = new ItemsChoiceType3[] { new ItemsChoiceType3(), new ItemsChoiceType3() };
                this.ItemsElementName[1] = ItemsChoiceType3.pCOFINS;
                vlCofins[1] = string.Format("{0:N2}", ObjNotaFiscalCofinsOutr.AliqCofins).ToString().Replace(".", "").Replace(",", ".");
                this.ItemsElementName[0] = ItemsChoiceType3.vBC;
                vlCofins[0] = string.Format("{0:N2}", ObjNotaFiscalCofinsOutr.ValorTotal).ToString().Replace(".", "").Replace(",", ".");

                this.Items = vlCofins;
            }
            else if (ObjNotaFiscalCofinsOutr.CSTPIS == "50")
                this.CST = TNFeInfNFeDetImpostoCOFINSCOFINSOutrCST.Item50;
            else if (ObjNotaFiscalCofinsOutr.CSTPIS == "51")
                this.CST = TNFeInfNFeDetImpostoCOFINSCOFINSOutrCST.Item51;
            else if (ObjNotaFiscalCofinsOutr.CSTPIS == "52")
                this.CST = TNFeInfNFeDetImpostoCOFINSCOFINSOutrCST.Item52;
            else if (ObjNotaFiscalCofinsOutr.CSTPIS == "53")
                this.CST = TNFeInfNFeDetImpostoCOFINSCOFINSOutrCST.Item53;
            else if (ObjNotaFiscalCofinsOutr.CSTPIS == "54")
                this.CST = TNFeInfNFeDetImpostoCOFINSCOFINSOutrCST.Item54;
            else if (ObjNotaFiscalCofinsOutr.CSTPIS == "55")
                this.CST = TNFeInfNFeDetImpostoCOFINSCOFINSOutrCST.Item55;
            else if (ObjNotaFiscalCofinsOutr.CSTPIS == "56")
                this.CST = TNFeInfNFeDetImpostoCOFINSCOFINSOutrCST.Item56;
            else if (ObjNotaFiscalCofinsOutr.CSTPIS == "60")
                this.CST = TNFeInfNFeDetImpostoCOFINSCOFINSOutrCST.Item60;
            else if (ObjNotaFiscalCofinsOutr.CSTPIS == "61")
                this.CST = TNFeInfNFeDetImpostoCOFINSCOFINSOutrCST.Item61;
            else if (ObjNotaFiscalCofinsOutr.CSTPIS == "62")
                this.CST = TNFeInfNFeDetImpostoCOFINSCOFINSOutrCST.Item62;
            else if (ObjNotaFiscalCofinsOutr.CSTPIS == "63")
                this.CST = TNFeInfNFeDetImpostoCOFINSCOFINSOutrCST.Item63;
            else if (ObjNotaFiscalCofinsOutr.CSTPIS == "64")
                this.CST = TNFeInfNFeDetImpostoCOFINSCOFINSOutrCST.Item64;
            else if (ObjNotaFiscalCofinsOutr.CSTPIS == "65")
                this.CST = TNFeInfNFeDetImpostoCOFINSCOFINSOutrCST.Item65;
            else if (ObjNotaFiscalCofinsOutr.CSTPIS == "66")
                this.CST = TNFeInfNFeDetImpostoCOFINSCOFINSOutrCST.Item66;
            else if (ObjNotaFiscalCofinsOutr.CSTPIS == "67")
                this.CST = TNFeInfNFeDetImpostoCOFINSCOFINSOutrCST.Item67;
            else if (ObjNotaFiscalCofinsOutr.CSTPIS == "70")
                this.CST = TNFeInfNFeDetImpostoCOFINSCOFINSOutrCST.Item70;
            else if (ObjNotaFiscalCofinsOutr.CSTPIS == "71")
                this.CST = TNFeInfNFeDetImpostoCOFINSCOFINSOutrCST.Item71;
            else if (ObjNotaFiscalCofinsOutr.CSTPIS == "72")
                this.CST = TNFeInfNFeDetImpostoCOFINSCOFINSOutrCST.Item72;
            else if (ObjNotaFiscalCofinsOutr.CSTPIS == "73")
                this.CST = TNFeInfNFeDetImpostoCOFINSCOFINSOutrCST.Item73;
            else if (ObjNotaFiscalCofinsOutr.CSTPIS == "74")
                this.CST = TNFeInfNFeDetImpostoCOFINSCOFINSOutrCST.Item74;
            else if (ObjNotaFiscalCofinsOutr.CSTPIS == "75")
                this.CST = TNFeInfNFeDetImpostoCOFINSCOFINSOutrCST.Item75;

            if (ObjNotaFiscalCofinsOutr.CSTPIS == "50")
            {
                string[] vlCofins = new string[2];
                this.ItemsElementName = new ItemsChoiceType3[] { new ItemsChoiceType3(), new ItemsChoiceType3() };
                this.ItemsElementName[0] = ItemsChoiceType3.vBC;
                vlCofins[0] = string.Format("{0:N2}", ObjNotaFiscalCofinsOutr.ValorTotal).ToString().Replace(".", "").Replace(",", ".");
                this.ItemsElementName[1] = ItemsChoiceType3.pCOFINS;
                vlCofins[1] = string.Format("{0:N2}", ObjNotaFiscalCofinsOutr.AliqCofins).ToString().Replace(".", "").Replace(",", ".");

                this.Items = vlCofins;
            }
            else if (ObjNotaFiscalCofinsOutr.CSTPIS == "99")
            {
                string[] vlCofins = new string[2];
                this.ItemsElementName = new ItemsChoiceType3[] { new ItemsChoiceType3(), new ItemsChoiceType3() };
                this.ItemsElementName[0] = ItemsChoiceType3.vBC;
                vlCofins[0] = string.Format("{0:N2}", ObjNotaFiscalCofinsOutr.ValorTotal).ToString().Replace(".", "").Replace(",", ".");
                this.ItemsElementName[1] = ItemsChoiceType3.pCOFINS;
                vlCofins[1] = string.Format("{0:N2}", ObjNotaFiscalCofinsOutr.AliqCofins).ToString().Replace(".", "").Replace(",", ".");

                this.Items = vlCofins;
            }

            this.vCOFINS = string.Format("{0:N2}", ObjNotaFiscalCofinsOutr.ValorCofins).ToString().Replace(",", ".");
        }
    }
    #endregion

    #endregion

    #endregion

    #region W. Total da NF-e
    public partial class TNFeInfNFeTotal
    {
        public TNFeInfNFeTotal() { }
        public TNFeInfNFeTotal(Entidade_NotaFiscal ObjNfeTotal)
        {
            this.ICMSTot = new TNFeInfNFeTotalICMSTot(ObjNfeTotal);
        }
    }
    public partial class TNFeInfNFeTotalICMSTot
    {
        public TNFeInfNFeTotalICMSTot() { }
        public TNFeInfNFeTotalICMSTot(Entidade_NotaFiscal ObjNfeICMSTot)
        {
            this.vBC = string.Format("{0:N2}", ObjNfeICMSTot.EntTotais.ValorBaseIcms).ToString().Replace(".", "").Replace(",", ".");
            this.vICMS = string.Format("{0:N2}", ObjNfeICMSTot.EntTotais.ValorIcms).ToString().Replace(".", "").Replace(",", ".");
            this.vICMSDeson = "0.00";
            this.vBCST = string.Format("{0:N2}", ObjNfeICMSTot.EntTotais.ValorIcmsBaseSub).ToString().Replace(".", "").Replace(",", ".");
            this.vST = string.Format("{0:N2}", ObjNfeICMSTot.EntTotais.ValorIcmsSub).ToString().Replace(".", "").Replace(",", ".");
            this.vProd = string.Format("{0:N2}", ObjNfeICMSTot.EntTotais.ValorTotalProdutos).ToString().Replace(".", "").Replace(",", ".");
            this.vFrete = string.Format("{0:N2}", ObjNfeICMSTot.EntTotais.ValorFrete).ToString().Replace(".", "").Replace(",", ".");
            this.vSeg = string.Format("{0:N2}", ObjNfeICMSTot.EntTotais.ValorSeguro).ToString().Replace(".", "").Replace(",", ".");
            this.vDesc = string.Format("{0:N2}", ObjNfeICMSTot.EntTotais.ValorDesconto).ToString().Replace(".", "").Replace(",", ".");
            this.vII = string.Format("{0:N2}", ObjNfeICMSTot.EntTotais.ValorII).ToString().Replace(".", "").Replace(",", ".");
            this.vIPI = string.Format("{0:N2}", ObjNfeICMSTot.EntTotais.ValorIpi).ToString().Replace(".", "").Replace(",", ".");
            this.vPIS = string.Format("{0:N2}", ObjNfeICMSTot.EntTotais.ValorPis).ToString().Replace(".", "").Replace(",", ".");
            this.vCOFINS = string.Format("{0:N2}", ObjNfeICMSTot.EntTotais.ValorCofins).ToString().Replace(".", "").Replace(",", ".");
            this.vOutro = string.Format("{0:N2}", ObjNfeICMSTot.EntTotais.ValorOutrasDesp).ToString().Replace(".", "").Replace(",", ".");
            this.vNF = string.Format("{0:N2}", ObjNfeICMSTot.EntTotais.ValorTotal).ToString().Replace(".", "").Replace(",", ".");
        }
    }
    #endregion

    #region X. Informações do Transporte da NF-e

    public partial class TNFeInfNFeTransp
    {
        public TNFeInfNFeTransp()
        {

        }
        public TNFeInfNFeTransp(Entidade_NotaFiscal ObjNfeTotal)
        {
            if (ObjNfeTotal.EntTransportador != null)
            {
                this.modFrete = TNFeInfNFeTranspModFrete.Item1;
                this.transporta = (new TNFeInfNFeTranspTransporta(ObjNfeTotal.EntTransportador));
            }
            else
            {
                this.modFrete = TNFeInfNFeTranspModFrete.Item9;
            }
        }
    }

    public partial class TNFeInfNFeTranspTransporta
    {
        public TNFeInfNFeTranspTransporta()
        {

        }
        public TNFeInfNFeTranspTransporta(Entidade_Transportador EntTrans)
        {
            if (EntTrans.CpfCnpj.Trim().Length == 14)
                this.ItemElementName = ItemChoiceType6.CNPJ;
            else
                this.ItemElementName = ItemChoiceType6.CPF;
            this.Item = EntTrans.CpfCnpj;
            this.xNome = EntTrans.RazaoSocial;
            if (EntTrans.IE.Trim() != string.Empty)
            {
                this.IE = EntTrans.IE;
                this.UF = (TUf)NegocioFuncoesGerais.RetornoCodigoUF(EntTrans.sUf);
            }

            this.xEnder = EntTrans.Lagradouro;
            this.xMun = EntTrans.sMunicipio;
        }
    }


    #endregion

    #region Y. Dados da Cobrança
    public partial class TNFeInfNFeCobr
    {
        public TNFeInfNFeCobr()
        { }
        public TNFeInfNFeCobr(Entidade_NotaFiscal ObjNfeCobranca)
        {

            List<TNFeInfNFeCobrDup> ListItem = new List<TNFeInfNFeCobrDup>();

            foreach (var item in ObjNfeCobranca.EntDuplicata)
            {
                ListItem.Add(new TNFeInfNFeCobrDup(item));
            }
            this.dup = ListItem.ToArray();
        }
    }
    public partial class TNFeInfNFeCobrDup
    {
        public TNFeInfNFeCobrDup()
        {

        }
        public TNFeInfNFeCobrDup(Entidade_Duplicatas ListDup)
        {
            this.nDup = ListDup.NumeroDup.ToString();
            this.dVenc = string.Format("{0:yyyy-MM-dd}", ListDup.DataVencimento);
            this.vDup = string.Format("{0:N2}", ListDup.ValorDup).ToString().Replace(".", "").Replace(",", ".");
        }
    }

    #endregion

    #region YA. Formas de Pagamento
    public partial class TNFeInfNFePag
    {
        public TNFeInfNFePag()
        {

        }
        public TNFeInfNFePag(Entidade_Duplicatas EntDocNFDup)
        {
            if (EntDocNFDup.TipoPagamento == 0)
                this.tPag = TNFeInfNFePagTPag.Item01;
            else
                this.tPag = TNFeInfNFePagTPag.Item03;
            this.vPag = string.Format("{0:N2}", EntDocNFDup.ValorDup).ToString().Replace(".", "").Replace(",", ".");
        }
    }

    #endregion

    #region Z. Informações Adicionais da NF-e
    public partial class TNFeInfNFeInfAdic
    {
        public TNFeInfNFeInfAdic()
        {

        }
        public TNFeInfNFeInfAdic(Entidade_NotaFiscal ObjNfeObs)
        {
            if (ObjNfeObs.sSerieNf.Trim() != "9")
                this.infAdFisco = ObjNfeObs.Observacao;
            else
                this.infCpl = ObjNfeObs.Observacao;
        }
    }
    #endregion
}
