//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.34014
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace Nfe.CCe {
    using Nfe.Entidade;
    using Nfe.Negocio.Geral;
    using System;
    using System.Xml.Serialization;

    public partial class TEvento
    {
        public TEvento()
        { }
        public TEvento(Entidade_ItemCCe EntItemCCe)
        {
            this.versao = "1.00";

            this.infEvento = new TEventoInfEvento(EntItemCCe);
        }
    }
    public partial class TEventoInfEvento
    {
        public TEventoInfEvento()
        { }
        public TEventoInfEvento(Entidade_ItemCCe EntItemCCeInf)
        {
            this.chNFe = EntItemCCeInf.TxChAcessoNfe;
            this.dhEvento = string.Format("{0:s}", Convert.ToDateTime(EntItemCCeInf.Dt_Prot_Nfe)) + "-03:00";

            this.Id = "ID110110" + EntItemCCeInf.TxChAcessoNfe + EntItemCCeInf.NrSeqEnvio.ToString().PadLeft(2, '0');
            this.cOrgao = (TCOrgaoIBGE)NegocioFuncoesGerais.RetornoCodigoIbge(EntItemCCeInf.CdUfCidadeIbge_Empresa);
            if (EntItemCCeInf.Ambiente.Trim() == "PROD")
                this.tpAmb = TAmb.Item1;                        // 1- Produção | 2 - Homologação
            else
                this.tpAmb = TAmb.Item2;
            this.ItemElementName = ItemChoiceType.CNPJ;     // DA EMPRESA EMITENTE
            this.Item = EntItemCCeInf.CdCpfCgc;
            this.tpEvento = TEventoInfEventoTpEvento.Item110110;
            this.nSeqEvento = EntItemCCeInf.NrSeqCount.ToString();
            this.verEvento = TEventoInfEventoVerEvento.Item100;
            this.detEvento = new TEventoInfEventoDetEvento(EntItemCCeInf);
        }
    }
    public partial class TEventoInfEventoDetEvento
    {
        public TEventoInfEventoDetEvento()
        {

        }
        public TEventoInfEventoDetEvento(Entidade_ItemCCe EntItemCCeDet)
        {
            this.versao = TEventoInfEventoDetEventoVersao.Item100;
            this.descEvento = TEventoInfEventoDetEventoDescEvento.CartadeCorrecao;
            this.xCorrecao = EntItemCCeDet.Desc_Correcao;
            this.xCondUso = TEventoInfEventoDetEventoXCondUso.ACartadeCorrecaoedisciplinadapeloparagrafo1oAdoart7odoConvenioSNde15dedezembrode1970epodeserutilizadapararegularizacaodeerroocorridonaemissaodedocumentofiscaldesdequeoerronaoestejarelacionadocomIasvariaveisquedeterminamovalordoimpostotaiscomobasedecalculoaliquotadiferencadeprecoquantidadevalordaoperacaooudaprestacaoIIacorrecaodedadoscadastraisqueimpliquemudancadoremetenteoudodestinatarioIIIadatadeemissaooudesaida;
        }
    }


}
