//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.34014
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace Nfe.envCCe
{
    using System.Xml.Serialization;
    using Nfe.Entidade;
    using System.Collections.Generic;
    using System;
    using Nfe.Negocio.Geral;

    public partial class TEnvEvento
    {
        public TEnvEvento()
        {

        }

        //public TEnvEvento(Entidade_CCe EntCCe)
        //{
        //    int i = 0;
        //    List<TEvento> ListTEvento = new List<TEvento>();

        //    TEvento ObjEnv;

        //    this.idLote = EntCCe.Id_CCe_Lote.ToString();
        //    this.versao = "1.00";
        //    foreach (var item in EntCCe.ItemCCe)
        //    {
        //        i += 1;
        //        ListTEvento.Add(new TEvento(item, i));
        //    }
        //    this.evento = ListTEvento.ToArray();
        //}
    }
    


}
