//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
using Nfe.Entidade;
using Nfe.Model;

namespace Nfe.downloadNFe
{

    public partial class TDownloadNFe
    {
        public TDownloadNFe()
        {

        }
        public TDownloadNFe(Entidade_DownloadNFe ObjEntDownload)
        {
            var DtLoja = FuncoesGerais.Loja(ObjEntDownload.id_loja);

            if (FuncoesGerais.TipoAmbiente() == "HOM")
                this.tpAmb = TAmb.Item2;
            else
                this.tpAmb = TAmb.Item1;
            this.chNFe = ObjEntDownload.ChaveNFe.ToArray();
            this.CNPJ = DtLoja.Rows[0]["cnpj"].ToString();
            this.versao = TVerDownloadNFe.Item100;
            this.xServ = TDownloadNFeXServ.DOWNLOADNFE;
        }
    }
}
