//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace Nfe.retDownloadNFe
{

    public partial class TRetDownloadNFe
    {
        public TRetDownloadNFe() { }
    }

    public partial class TRetDownloadNFeRetNFe
    {
        public TRetDownloadNFeRetNFe() { }
    }
    public partial class TRetDownloadNFeRetNFeProcNFe
    {
        public TRetDownloadNFeRetNFeProcNFe() { }
    }
    public partial class TRetDownloadNFeRetNFeProcNFeGrupoZip
    {
        public TRetDownloadNFeRetNFeProcNFeGrupoZip() { }
    }
}
