//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.34011
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace Nfe.InutNFe
{
    using System.Xml.Serialization;
    using Nfe.Entidade;
    using System;
    using Nfe.Negocio.Geral;
    public partial class TInutNFe
    {
        
        public TInutNFe()
        {

        }
        public TInutNFe(Entidade_Inutilizacao objEntInut)
        {
            this.versao = "3.10";
            this.infInut = new TInutNFeInfInut(objEntInut);
        }
    }
    public partial class TInutNFeInfInut
    {
        public TInutNFeInfInut()
        {
        }
        public TInutNFeInfInut(Entidade_Inutilizacao objEntInutDados)
        {
            this.Id = "ID" + objEntInutDados.cUf + string.Format("{0:yy}", DateTime.Now) + objEntInutDados.Cnpj + objEntInutDados.ModNfe + objEntInutDados.sSerieNf.PadLeft(3,'0') + objEntInutDados.NrIni.ToString().PadLeft(9, '0') + objEntInutDados.NrFim.ToString().PadLeft(9, '0');
            this.ano = string.Format("{0:yy}", DateTime.Now);
            if (objEntInutDados.TpAmbiente == "PROD")
                this.tpAmb = TAmb.Item1;
            else
                this.tpAmb = TAmb.Item2;
            this.xServ = TInutNFeInfInutXServ.INUTILIZAR;
            this.cUF = (TCodUfIBGE)NegocioFuncoesGerais.RetornoCodigoIbge(objEntInutDados.cUf);
            if (objEntInutDados.ModNfe == 55)
                this.mod = TMod.Item55;
            else
                this.mod = TMod.Item65;
            this.serie = objEntInutDados.sSerieNf;
            this.CNPJ = objEntInutDados.Cnpj;
            this.nNFIni = objEntInutDados.NrIni.ToString();
            this.nNFFin = objEntInutDados.NrFim.ToString();
            this.xJust = "Numeração não utilizada";
        }
    }

}
