//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.34011
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace Nfe.RetInutNFe {
    using System.Xml.Serialization;


    public partial class TRetInutNFe
    {
        //public TRetInutNFe()
        //{
        //    this.versao = "3.10";

        //}
    }
}
