//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.34011
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace Nfe.retConsSitNFe
{
    using System.Xml.Serialization;

    public partial class TRetConsSitNFe
    {

    }

    public partial class TProtNFe
    {

    }
    public partial class TProtNFeInfProt
    {
    }
    public partial class TRetEvento
    {
    }
    public partial class TRetEventoInfEvento
    {
    }
    public partial class TEvento
    {
    }
    public partial class TEventoInfEvento
    {
    }
    public partial class TEventoInfEventoDetEvento
    {
    }
    public partial class TProcEvento
    {
    }
    public partial class TRetCancNFe
    {
    }
    public partial class TRetCancNFeInfCanc
    {
    }

}
