//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.269
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace Nfe.envEventoCancNFe
{
    using System.Xml.Serialization;
    using System.Data;
    using System.Collections.Generic;

    using Nfe.Entidade;
    using Nfe.Negocio.Geral;
    using System;

    public partial class TEnvEvento
    {
        Entidade_Cancelamento nfCanc;

        public TEnvEvento()
        {
        }

        int i = 1;
        public TEnvEvento(int idLoteCancelamento, string Ambiente, Entidade_Cancelamento eCancelamento)
        {

            this.idLote = eCancelamento.id.ToString();

            eCancelamento.Ambiente = Ambiente;
            this.versao = "1.00";

            List<TEvento> listInfEvento = new List<TEvento>();

            listInfEvento.Add(new TEvento(eCancelamento));

            this.evento = listInfEvento.ToArray();

        }
    }
    public partial class TEvento
    {
        public TEvento()
        {
        }
        public TEvento(Entidade_Cancelamento EvenCancelamento)
        {
            this.versao = "1.00";

            this.infEvento = new TEventoInfEvento(EvenCancelamento);
        }
    }
    public partial class TEventoInfEvento
    {
        public TEventoInfEvento()
        {
        }
        public TEventoInfEvento(Entidade_Cancelamento EvenInfCancelamento)
        {
            this.Id = "ID110111" + EvenInfCancelamento.ChaveAcessoNfe + "01";
            this.cOrgao = (TCOrgaoIBGE)NegocioFuncoesGerais.RetornoCodigoIbge(Convert.ToInt32(EvenInfCancelamento.CodigoIbgeEmpresa.Substring(0, EvenInfCancelamento.CodigoIbgeEmpresa.Length - 5)));

            if (EvenInfCancelamento.Ambiente == "PROD")
                this.tpAmb = TAmb.Item1;
            else
                this.tpAmb = TAmb.Item2;

            this.chNFe = EvenInfCancelamento.ChaveAcessoNfe;

            this.ItemElementName = ItemChoiceType.CNPJ;

            this.Item = EvenInfCancelamento.CnpjCpf;
            ////if (EvenInfCancelamento.Ambiente == "PROD")
            //this.Item = EvenInfCancelamento.CnpjCpf;
            ////else
            // //   this.Item = "06317980000137";

            this.dhEvento = string.Format("{0:s}", Convert.ToDateTime(EvenInfCancelamento.DataHora)) + "-03:00";
            this.tpEvento = TEventoInfEventoTpEvento.Item110111;
            this.nSeqEvento = "1";
            this.verEvento = TEventoInfEventoVerEvento.Item100;

            this.detEvento = new TEventoInfEventoDetEvento(EvenInfCancelamento);
        }
    }
    public partial class TEventoInfEventoDetEvento
    {
        public TEventoInfEventoDetEvento()
        {
        }
        public TEventoInfEventoDetEvento(Entidade_Cancelamento EvenInfCancelamento)
        {
            this.descEvento = TEventoInfEventoDetEventoDescEvento.Cancelamento;
            this.nProt = EvenInfCancelamento.ProtocoloAutoriz;
            this.versao = TEventoInfEventoDetEventoVersao.Item100;
            this.xJust = EvenInfCancelamento.Justificatica;
        }
    }
}
