//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.34014
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace Nfe.retEnvEventoCancNFe {
    using System.Xml.Serialization;

    public partial class TRetEnvEvento
    {
        public TRetEnvEvento()
        {

        }
    }
    public partial class TRetEvento 
    {
        public TRetEvento()
        {

        }

    }
    
}
