//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
using Nfe.Model;

namespace Nfe.consNFeDest
{

    public partial class TConsNFeDest
    {
        public TConsNFeDest()
        {


        }
        public TConsNFeDest(int loja)
        {
            var DtLoja = FuncoesGerais.Loja(loja);

            this.versao = TVeConsNFeDest.Item101;
            if (FuncoesGerais.TipoAmbiente() == "HOM")
                this.tpAmb = TAmb.Item2;
            else
                this.tpAmb = TAmb.Item1;

            this.xServ = TConsNFeDestXServ.CONSULTARNFEDEST;
            this.CNPJ = DtLoja.Rows[0]["cnpj"].ToString();
            this.indNFe = TConsNFeDestIndNFe.Item0;
            this.indEmi = TConsNFeDestIndEmi.Item1;
            this.ultNSU = "0";
        }
    }
}
