//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace Nfe.retconsNFeDest
{

    public partial class TRetConsNFeDest
    {
        public TRetConsNFeDest() { }
    }
    public partial class TRetConsNFeDestRet
    {
        public TRetConsNFeDestRet() { }
    }
    public partial class TRetConsNFeDestRetResCCe
    {
        public TRetConsNFeDestRetResCCe() { }
    }
    public partial class TRetConsNFeDestRetResCanc
    {
        public TRetConsNFeDestRetResCanc() { }
    }
    public partial class TRetConsNFeDestRetResNFe
    {
        public TRetConsNFeDestRetResNFe() { }
    }
}
