//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace Nfe.retconsNFeDest {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.portalfiscal.inf.br/nfe")]
    [System.Xml.Serialization.XmlRootAttribute("retConsNFeDest", Namespace="http://www.portalfiscal.inf.br/nfe", IsNullable=false)]
    public partial class TRetConsNFeDest {
        
        private TAmb tpAmbField;
        
        private string verAplicField;
        
        private string cStatField;
        
        private string xMotivoField;
        
        private System.DateTime dhRespField;
        
        private TRetConsNFeDestIndCont indContField;
        
        private bool indContFieldSpecified;
        
        private string ultNSUField;
        
        private TRetConsNFeDestRet[] retField;
        
        private TVeConsNFeDest versaoField;
        
        /// <remarks/>
        public TAmb tpAmb {
            get {
                return this.tpAmbField;
            }
            set {
                this.tpAmbField = value;
            }
        }
        
        /// <remarks/>
        public string verAplic {
            get {
                return this.verAplicField;
            }
            set {
                this.verAplicField = value;
            }
        }
        
        /// <remarks/>
        public string cStat {
            get {
                return this.cStatField;
            }
            set {
                this.cStatField = value;
            }
        }
        
        /// <remarks/>
        public string xMotivo {
            get {
                return this.xMotivoField;
            }
            set {
                this.xMotivoField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime dhResp {
            get {
                return this.dhRespField;
            }
            set {
                this.dhRespField = value;
            }
        }
        
        /// <remarks/>
        public TRetConsNFeDestIndCont indCont {
            get {
                return this.indContField;
            }
            set {
                this.indContField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool indContSpecified {
            get {
                return this.indContFieldSpecified;
            }
            set {
                this.indContFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string ultNSU {
            get {
                return this.ultNSUField;
            }
            set {
                this.ultNSUField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ret")]
        public TRetConsNFeDestRet[] ret {
            get {
                return this.retField;
            }
            set {
                this.retField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public TVeConsNFeDest versao {
            get {
                return this.versaoField;
            }
            set {
                this.versaoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.portalfiscal.inf.br/nfe")]
    public enum TAmb {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.portalfiscal.inf.br/nfe")]
    public enum TRetConsNFeDestIndCont {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.portalfiscal.inf.br/nfe")]
    public partial class TRetConsNFeDestRet {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("resCCe", typeof(TRetConsNFeDestRetResCCe))]
        [System.Xml.Serialization.XmlElementAttribute("resCanc", typeof(TRetConsNFeDestRetResCanc))]
        [System.Xml.Serialization.XmlElementAttribute("resNFe", typeof(TRetConsNFeDestRetResNFe))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.portalfiscal.inf.br/nfe")]
    public partial class TRetConsNFeDestRetResCCe {
        
        private string chNFeField;
        
        private string dhEventoField;
        
        private TRetConsNFeDestRetResCCeTpEvento tpEventoField;
        
        private string nSeqEventoField;
        
        private TRetConsNFeDestRetResCCeDescEvento descEventoField;
        
        private string xCorrecaoField;
        
        private TRetConsNFeDestRetResCCeTpNF tpNFField;
        
        private System.DateTime dhRecbtoField;
        
        private string nSUField;
        
        /// <remarks/>
        public string chNFe {
            get {
                return this.chNFeField;
            }
            set {
                this.chNFeField = value;
            }
        }
        
        /// <remarks/>
        public string dhEvento {
            get {
                return this.dhEventoField;
            }
            set {
                this.dhEventoField = value;
            }
        }
        
        /// <remarks/>
        public TRetConsNFeDestRetResCCeTpEvento tpEvento {
            get {
                return this.tpEventoField;
            }
            set {
                this.tpEventoField = value;
            }
        }
        
        /// <remarks/>
        public string nSeqEvento {
            get {
                return this.nSeqEventoField;
            }
            set {
                this.nSeqEventoField = value;
            }
        }
        
        /// <remarks/>
        public TRetConsNFeDestRetResCCeDescEvento descEvento {
            get {
                return this.descEventoField;
            }
            set {
                this.descEventoField = value;
            }
        }
        
        /// <remarks/>
        public string xCorrecao {
            get {
                return this.xCorrecaoField;
            }
            set {
                this.xCorrecaoField = value;
            }
        }
        
        /// <remarks/>
        public TRetConsNFeDestRetResCCeTpNF tpNF {
            get {
                return this.tpNFField;
            }
            set {
                this.tpNFField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime dhRecbto {
            get {
                return this.dhRecbtoField;
            }
            set {
                this.dhRecbtoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NSU {
            get {
                return this.nSUField;
            }
            set {
                this.nSUField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.portalfiscal.inf.br/nfe")]
    public enum TRetConsNFeDestRetResCCeTpEvento {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("110110")]
        Item110110,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.portalfiscal.inf.br/nfe")]
    public enum TRetConsNFeDestRetResCCeDescEvento {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Carta de Correção")]
        CartadeCorreção,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Carta de Correcao")]
        CartadeCorrecao,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.portalfiscal.inf.br/nfe")]
    public enum TRetConsNFeDestRetResCCeTpNF {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.portalfiscal.inf.br/nfe")]
    public partial class TRetConsNFeDestRetResCanc {
        
        private string chNFeField;
        
        private string itemField;
        
        private ItemChoiceType1 itemElementNameField;
        
        private string xNomeField;
        
        private string ieField;
        
        private string dEmiField;
        
        private TRetConsNFeDestRetResCancTpNF tpNFField;
        
        private string vNFField;
        
        private string digValField;
        
        private System.DateTime dhRecbtoField;
        
        private TRetConsNFeDestRetResCancCSitNFe cSitNFeField;
        
        private TRetConsNFeDestRetResCancCSitConf cSitConfField;
        
        private string nSUField;
        
        /// <remarks/>
        public string chNFe {
            get {
                return this.chNFeField;
            }
            set {
                this.chNFeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CNPJ", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("CPF", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType1 ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
        
        /// <remarks/>
        public string xNome {
            get {
                return this.xNomeField;
            }
            set {
                this.xNomeField = value;
            }
        }
        
        /// <remarks/>
        public string IE {
            get {
                return this.ieField;
            }
            set {
                this.ieField = value;
            }
        }
        
        /// <remarks/>
        public string dEmi {
            get {
                return this.dEmiField;
            }
            set {
                this.dEmiField = value;
            }
        }
        
        /// <remarks/>
        public TRetConsNFeDestRetResCancTpNF tpNF {
            get {
                return this.tpNFField;
            }
            set {
                this.tpNFField = value;
            }
        }
        
        /// <remarks/>
        public string vNF {
            get {
                return this.vNFField;
            }
            set {
                this.vNFField = value;
            }
        }
        
        /// <remarks/>
        public string digVal {
            get {
                return this.digValField;
            }
            set {
                this.digValField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime dhRecbto {
            get {
                return this.dhRecbtoField;
            }
            set {
                this.dhRecbtoField = value;
            }
        }
        
        /// <remarks/>
        public TRetConsNFeDestRetResCancCSitNFe cSitNFe {
            get {
                return this.cSitNFeField;
            }
            set {
                this.cSitNFeField = value;
            }
        }
        
        /// <remarks/>
        public TRetConsNFeDestRetResCancCSitConf cSitConf {
            get {
                return this.cSitConfField;
            }
            set {
                this.cSitConfField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NSU {
            get {
                return this.nSUField;
            }
            set {
                this.nSUField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.portalfiscal.inf.br/nfe", IncludeInSchema=false)]
    public enum ItemChoiceType1 {
        
        /// <remarks/>
        CNPJ,
        
        /// <remarks/>
        CPF,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.portalfiscal.inf.br/nfe")]
    public enum TRetConsNFeDestRetResCancTpNF {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.portalfiscal.inf.br/nfe")]
    public enum TRetConsNFeDestRetResCancCSitNFe {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.portalfiscal.inf.br/nfe")]
    public enum TRetConsNFeDestRetResCancCSitConf {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.portalfiscal.inf.br/nfe")]
    public partial class TRetConsNFeDestRetResNFe {
        
        private string chNFeField;
        
        private string itemField;
        
        private ItemChoiceType itemElementNameField;
        
        private string xNomeField;
        
        private string ieField;
        
        private string dEmiField;
        
        private TRetConsNFeDestRetResNFeTpNF tpNFField;
        
        private string vNFField;
        
        private string digValField;
        
        private System.DateTime dhRecbtoField;
        
        private TRetConsNFeDestRetResNFeCSitNFe cSitNFeField;
        
        private TRetConsNFeDestRetResNFeCSitConf cSitConfField;
        
        private string nSUField;
        
        /// <remarks/>
        public string chNFe {
            get {
                return this.chNFeField;
            }
            set {
                this.chNFeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CNPJ", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("CPF", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
            }
        }
        
        /// <remarks/>
        public string xNome {
            get {
                return this.xNomeField;
            }
            set {
                this.xNomeField = value;
            }
        }
        
        /// <remarks/>
        public string IE {
            get {
                return this.ieField;
            }
            set {
                this.ieField = value;
            }
        }
        
        /// <remarks/>
        public string dEmi {
            get {
                return this.dEmiField;
            }
            set {
                this.dEmiField = value;
            }
        }
        
        /// <remarks/>
        public TRetConsNFeDestRetResNFeTpNF tpNF {
            get {
                return this.tpNFField;
            }
            set {
                this.tpNFField = value;
            }
        }
        
        /// <remarks/>
        public string vNF {
            get {
                return this.vNFField;
            }
            set {
                this.vNFField = value;
            }
        }
        
        /// <remarks/>
        public string digVal {
            get {
                return this.digValField;
            }
            set {
                this.digValField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime dhRecbto {
            get {
                return this.dhRecbtoField;
            }
            set {
                this.dhRecbtoField = value;
            }
        }
        
        /// <remarks/>
        public TRetConsNFeDestRetResNFeCSitNFe cSitNFe {
            get {
                return this.cSitNFeField;
            }
            set {
                this.cSitNFeField = value;
            }
        }
        
        /// <remarks/>
        public TRetConsNFeDestRetResNFeCSitConf cSitConf {
            get {
                return this.cSitConfField;
            }
            set {
                this.cSitConfField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NSU {
            get {
                return this.nSUField;
            }
            set {
                this.nSUField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.portalfiscal.inf.br/nfe", IncludeInSchema=false)]
    public enum ItemChoiceType {
        
        /// <remarks/>
        CNPJ,
        
        /// <remarks/>
        CPF,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.portalfiscal.inf.br/nfe")]
    public enum TRetConsNFeDestRetResNFeTpNF {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.portalfiscal.inf.br/nfe")]
    public enum TRetConsNFeDestRetResNFeCSitNFe {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.portalfiscal.inf.br/nfe")]
    public enum TRetConsNFeDestRetResNFeCSitConf {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.portalfiscal.inf.br/nfe")]
    public enum TVeConsNFeDest {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1.01")]
        Item101,
    }
}
