//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.34011
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace Nfe.RetConsStatServ {
    using System.Xml.Serialization;

    public partial class TRetConsStatServ
    {
        public TRetConsStatServ()
        {

        }
        public TRetConsStatServ(object obj)
        {
            this.cStat = "";
            this.cUF = TCodUfIBGE.Item11;
            this.dhRecbto = string.Empty;
            this.dhRetorno = string.Empty;
            this.tMed = string.Empty;
            this.tpAmb = TAmb.Item1;
            this.verAplic = string.Empty;
            this.versao = string.Empty;
            this.xMotivo = string.Empty;
            this.xObs = string.Empty;
        }
    }

}
